week6/day2/taskly_ironhack/config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :users
  resources :tasks

  match '/signup',    to: 'users#new',    via: 'get'

  namespace :api do
    namespace :v1 do
      resources :users, except: [:new, :edit] do
        resources :tasks, except: [:new, :edit]
        post 'tasks/:id/complete', to: 'tasks#complete'
      end
    end
  end

end

week6/day2/taskly_ironhack/app/models/api/v1.rb
module Api::V1
  def self.table_name_prefix
    'api_v1_'
  end
end

week6/day2/taskly_ironhack/app/models/api/v1/task.rb
class Api::V1::Task < ActiveRecord::Base
end

week6/day2/taskly_ironhack/app/models/task.rb
class Task < ActiveRecord::Base
	belongs_to :user

	validates :name,  		presence: true, length: { maximum: 250 }
	validates :due_date, 	presence: true
	validates :user_id, 	presence: true

	def complete!
		self.complete = true
		self
	end

	def as_json(options={})
	  super(except: [ :created_at, :updated_at])
	end
end

week6/day2/taskly_ironhack/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
	before_save { self.email = email.downcase }

	validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }


	has_many :tasks


	

	def as_json(options={})
  	super( only: [:name,:email],
    	methods: [:tasks_count],
    	include: [tasks:  { only: :name }])
	end

	def tasks_count
		self.tasks.count
	end
end

week6/day2/taskly_ironhack/app/controllers/api/v1/tasks_controller.rb
class Api::V1::TasksController < ApplicationController
	before_action :user_exists

	def index
		tasks = @user.tasks
		render json: tasks
	end


	def create
		task = @user.tasks.build(task_params)
		task.save
		render json: task
	end

	def show
		task = @user.tasks.find_by(id: params[:id])
		unless task
			render json: { error: "task not found"}, status: 400
			return
		end
		render json: task
	end

	def complete
		task = @user.tasks.find_by(id: params[:id])
		unless task
			render json: { :error => "task not found"}, status: 400
			return
		end
		task.complete! 
		task.save
		render json: task
	end

	private

	def task_params
		params.require(:task).permit(:name, :due_date)
	end

	def user_exists
	  @user = User.find_by(id: params[:user_id])
		unless @user
			render json: { error: "user not found"}, status: 400
			return
		end 
	end
end

week6/day2/taskly_ironhack/app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < ApplicationController
	def index
		users = User.all
		render json: users
	end


	def create
		user = User.create(user_params)
		render json: user, except: [:id] 
	end

	def show
		user = User.find_by(id: params[:id])
		unless user
			render json: { error: "user not found"}, status: 400
			return
		end
		render json: user
	end

	def update
		user = User.find_by(id: params[:id])
		unless user
			render json: { error: "user not found"}, status: 400
			return
		end
		user.update(user_params)
		render json: user
	end

	def destroy
		user = User.find_by(id: params[:id])
		unless user
			render json: { error: "user not found"}, status: 400
			return
		end
		user.destroy
		render json: user
	end


	private

	def user_params
		params.require(:user).permit(:name, :email)
	end

end

week6/day2/taskly_ironhack/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.

  class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    end
end


  unless Rails.env.development?
  	protect_from_forgery with: :exception
  end
  
end

week6/day2/taskly_ironhack/app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  # GET /tasks
  def index
    @tasks = Task.all
  end

  # GET /tasks/1
  def show
    @task = Task.find(params[:id])
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
    @task = Task.find(params[:id])
  end

  # POST /tasks
  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /tasks/1
  def update
    @task = Task.find(params[:id])
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /tasks/1
  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
    end
  end

  private

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:name, :due_date, :completed, :user_id)
    end
end

week6/day2/taskly_ironhack/app/controllers/users_controller.rb
class UsersController < ApplicationController

  # GET /users
  def index
    @users = User.all
  end

  # GET /users/1
  def show
    @user = User.find(params[:id])
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /users/1
  def update
    @user = User.find(params[:id])
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /users/1
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
    end
  end

  private
  
    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email)
    end
end

week6/day2/taskly_ironhack/app/helpers/api/v1/tasks_helper.rb
module Api::V1::TasksHelper
end

week6/day2/taskly_ironhack/app/helpers/users_helper.rb
module UsersHelper
end

week6/day2/taskly_ironhack/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Taskly</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>
	<p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

<%= debug(params) if Rails.env.development? %>
</body>
</html>

week6/day2/taskly_ironhack/app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :due_date %><br>
    <%= f.datetime_select :due_date %>
  </div>
  <div class="field">
    <%= f.label :completed %><br>
    <%= f.check_box :completed %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

week6/day2/taskly_ironhack/app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form' %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

week6/day2/taskly_ironhack/app/views/tasks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Tasks</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Due date</th>
      <th>Completed</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.name %></td>
        <td><%= task.due_date %></td>
        <td><%= task.completed %></td>
        <td><%= task.user_id %></td>
        <td><%= link_to 'Show', task %></td>
        <td><%= link_to 'Edit', edit_task_path(task) %></td>
        <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Task', new_task_path %>

week6/day2/taskly_ironhack/app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form' %>

<%= link_to 'Back', tasks_path %>

week6/day2/taskly_ironhack/app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @task.name %>
</p>

<p>
  <strong>Due date:</strong>
  <%= @task.due_date %>
</p>

<p>
  <strong>Completed:</strong>
  <%= @task.completed %>
</p>

<p>
  <strong>User:</strong>
  <%= @task.user_id %>
</p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>

week6/day2/taskly_ironhack/app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

week6/day2/taskly_ironhack/app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

week6/day2/taskly_ironhack/app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

week6/day2/taskly_ironhack/app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

week6/day2/taskly_ironhack/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>