week4/day4/twatter/config/routes.rb
Rails.application.routes.draw do
  
  resources :users
  root "twats#index"
  get "projects/new", to: "projects#new"
  get "projects/index", to: "projects#index"
  post "projects/create", to: "projects#create"
  

  resources :twats
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

week4/day4/twatter/app/models/twat.rb
class Twat < ApplicationRecord
	validates :body, presence: true 
	validates :body, format: { with: /\A[a-zA-Z0-9]+\Z/, message: "cannot contain white spaces"}
end

week4/day4/twatter/app/models/user.rb
class User < ApplicationRecord
	validates :name, presence: true
	validates :username, format: { with: /\A[a-zA-Z0-9]+\Z/ ,  message: "cannot contain white spaces"}
	
 end

week4/day4/twatter/app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	def index
	end

	def new
		@twat = Twat.new

	end

	def create
		@twat = Twat.new(params[:twat].permit(:body))
		if @twat.save
			flash[:notice] = "Bien has twateado"
			redirect_to projects_index_path
		else

			render :new
		end

	end

end

week4/day4/twatter/app/controllers/twats_controller.rb
class TwatsController < ApplicationController
  before_action :set_twat, only: [:show, :edit, :update, :destroy]

  # GET /twats
  # GET /twats.json
  def index
    @twats = Twat.all
  end

  # GET /twats/1
  # GET /twats/1.json
  def show
  end

  # GET /twats/new
  def new
    @twat = Twat.new
  end

  # GET /twats/1/edit
  def edit
  end

  # POST /twats
  # POST /twats.json
  def create
    @twat = Twat.new(twat_params)

    respond_to do |format|
      if @twat.save
        format.html { redirect_to @twat, notice: 'Twat was successfully created.' }
        format.json { render :show, status: :created, location: @twat }
      else
        format.html { render :new }
        format.json { render json: @twat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /twats/1
  # PATCH/PUT /twats/1.json
  def update
    respond_to do |format|
      if @twat.update(twat_params)
        format.html { redirect_to @twat, notice: 'Twat was successfully updated.' }
        format.json { render :show, status: :ok, location: @twat }
      else
        format.html { render :edit }
        format.json { render json: @twat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /twats/1
  # DELETE /twats/1.json
  def destroy
    @twat.destroy
    respond_to do |format|
      format.html { redirect_to twats_url, notice: 'Twat was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_twat
      @twat = Twat.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def twat_params
      params.require(:twat).permit(:body)
    end
end

week4/day4/twatter/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :username, :email, :bio)
    end
end

week4/day4/twatter/app/helpers/twats_helper.rb
module TwatsHelper
end

week4/day4/twatter/app/views/projects/index.html.erb
<%= link_to "New twat", projects_new_path %>

week4/day4/twatter/app/views/projects/new.html.erb
<% if @twat.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@twat.errors.count, "error") %> prohibited this twat from being saved:</h2>

      <ul>
      <% @twat.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<%= form_for(@twat, url: '/projects/create')  do |f| %>
  Body: <%= f.text_field :body%>
  <%= f.submit %>
<% end %>

week4/day4/twatter/app/views/twats/_form.html.erb
<%= form_for(twat) do |f| %>
  <% if twat.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(twat.errors.count, "error") %> prohibited this twat from being saved:</h2>

      <ul>
      <% twat.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :body %>
    <%= f.text_field :body %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

week4/day4/twatter/app/views/twats/edit.html.erb
<h1>Editing Twat</h1>

<%= render 'form', twat: @twat %>

<%= link_to 'Show', @twat %> |
<%= link_to 'Back', twats_path %>

week4/day4/twatter/app/views/twats/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Twats</h1>

<table>
  <thead>
    <tr>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @twats.each do |twat| %>
      <tr>
        <td><%= twat.body %></td>
        <td><%= link_to 'Show', twat %></td>
        <td><%= link_to 'Edit', edit_twat_path(twat) %></td>
        <td><%= link_to 'Destroy', twat, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Twat', new_twat_path %>

week4/day4/twatter/app/views/twats/new.html.erb
<h1>New Twat</h1>

<%= render 'form', twat: @twat %>

<%= link_to 'Back', twats_path %>

week4/day4/twatter/app/views/twats/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Body:</strong>
  <%= @twat.body %>
</p>

<%= link_to 'Edit', edit_twat_path(@twat) %> |
<%= link_to 'Back', twats_path %>